services:
  - type: web
    name: lineas-moviles
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
